#ifndef RDK_ERROR_CODES_H
#define RDK_ERROR_CODES_H

#ifndef RDK_ERROR_CODES
#define RDK_ERROR_CODES

#define RDK_UNHANDLED_EXCEPTION 0x01000000 // Не удалось записать исключение в лог
#define RDK_EXCEPTION_CATCHED 0x01000001 // Произошло исключение и информация о нем была записана в лог
#define RDK_SUCCESS 0
#define RDK_NOT_IMPLEMENTED 1

/// Core errors
#define RDK_E_CORE_INIT_FAIL 100
#define RDK_E_CORE_INCORRECT_CHANNELS_NUMBER 101
#define RDK_E_CORE_CHANNEL_NOT_FOUND 102
#define RDK_E_CORE_ZERO_CHANNEL_MUST_EXIST 103
#define RDK_E_CORE_ENGINE_CREATE_FAIL 104
#define RDK_E_CORE_STORAGE_CREATE_FAIL 105
#define RDK_E_CORE_ENVIRONMENT_CREATE_FAIL 106
#define RDK_E_CORE_ENGINE_INIT_FAIL 107
#define RDK_E_CORE_ENVIRONMENT_UNINIT_FAIL 108

/// Storage errors
#define RDK_E_STORAGE_LOAD_COMMON_CLASSES_DESCR_FAIL 200
#define RDK_E_STORAGE_DEL_COLLECTION_FAIL 201
#define RDK_E_STORAGE_COLLECTION_NOT_FOUND 202
#define RDK_E_STORAGE_ADD_COLLECTION_FAIL 203
#define RDK_E_STORAGE_BUILD_FAIL 204
#define RDK_E_STORAGE_RT_COLLECTION_CREATION_FAIL 250

/// Environment errors

/// Model errors
#define RDK_E_MODEL_COMPONENT_NOT_FOUND 400

/// Engine errors

/// XML Parser erros
#define RDK_E_XML_TARGET_NODE_NOT_FOUND 1000

#endif

#endif

