cmake_minimum_required(VERSION 3.16)

# Unit tests for UProperty
add_subdirectory(UProperty)

# Unit tests for UComponent
add_subdirectory(UComponent)

# Unit tests for UContainer
add_subdirectory(UContainer)

# Unit tests for UStorage
add_subdirectory(UStorage)

# Logging tests
add_subdirectory(Logging)
